image: Visual Studio 2019
version: 2.0.{build}
configuration: Release

init:
- if "%APPVEYOR_REPO_NAME%" == "JeremyAnsel/JeremyAnsel.IO.Locator" if "%APPVEYOR_REPO_BRANCH%"=="master" if not defined APPVEYOR_PULL_REQUEST_NUMBER set DEPLOY=True

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'

environment:
  GITHUB_TOKEN:
    secure: awbDbCVBldNyz+7VzGnSLlBnczS0NtXrUaS7UkrwoOoUIAzE70QHYfKQuTyOJavb

nuget:
  disable_publish_on_pr: true

before_build:
- nuget restore JeremyAnsel.IO.Locator\JeremyAnsel.IO.Locator.sln

build:
  project: JeremyAnsel.IO.Locator\JeremyAnsel.IO.Locator.sln
  publish_nuget: true
  verbosity: minimal

after_build:
- if not defined APPVEYOR_PULL_REQUEST_NUMBER 7z a JeremyAnsel.IO.Locator.Documentation.zip .\JeremyAnsel.IO.Locator\Documentation\_site\* > nul
- if not defined APPVEYOR_PULL_REQUEST_NUMBER appveyor PushArtifact JeremyAnsel.IO.Locator.Documentation.zip

test_script:
- JeremyAnsel.IO.Locator\run-tests.cmd

deploy:
- provider: NuGet
  api_key:
    secure: ez3RLsSaraf05zX77AqWyz+gYbT+5eM7jdIq7Fv43DXPp5+YscPbW5yb7owDfyHd
  skip_symbols: true
  on:
    branch: master
    DEPLOY: True

after_deploy:
- if "%DEPLOY%" == "True" git clone -q --branch=gh-pages --depth 5 git://github.com/JeremyAnsel/JeremyAnsel.IO.Locator.git gh-pages
- if "%DEPLOY%" == "True" cd gh-pages
- if "%DEPLOY%" == "True" git checkout -qf gh-pages
- if "%DEPLOY%" == "True" git config core.safecrlf false
- if "%DEPLOY%" == "True" git config push.default simple
- "if \"%DEPLOY%\" == \"True\" git config user.name \"Jérémy Ansel\""
- if "%DEPLOY%" == "True" git config user.email JeremyAnsel@users.noreply.github.com
- if "%DEPLOY%" == "True" xcopy /s /y /q ..\JeremyAnsel.IO.Locator\Documentation\_site .
- if "%DEPLOY%" == "True" git add --all . > nul
- if "%DEPLOY%" == "True" git commit -m "Update doc generated by CI"
- if "%DEPLOY%" == "True" if exist coverage rd /s /q coverage
- if "%DEPLOY%" == "True" md coverage
- if "%DEPLOY%" == "True" xcopy /s /y /q ..\JeremyAnsel.IO.Locator\bld\coverage coverage
- if "%DEPLOY%" == "True" git add --all coverage > nul
- if "%DEPLOY%" == "True" git commit -m "Update code coverage generated by CI"
- if "%DEPLOY%" == "True" git push -q https://%GITHUB_TOKEN%@github.com/JeremyAnsel/JeremyAnsel.IO.Locator.git
